### ISSUE TITLE
Compatible with G16?

### ISSUE THREAD

**Issue by abbottjlu** [jzpathfinder/pysoc#2]
The output file created by rwfdump in G09 and G16 are different. 

Does the current script compatible with G16 output? 

If not, how to modify the script? 

Do I need to edit the lines from 161 to 235 in "soc.py" file? 

Would you please modify the script to compatible with G16 output?  
Anyway, G16 is quite fast in TDDFT calculation.

**Comment by gaox-qd** [comment]
@abbottjlu 
Thanks for your message. 
I'm sorry I don't know what exactly the difference between G16 and G09 outputs since I don't have the G16 version.
But I checked the online RWF of G16, the keywords I used in PySOC are the same as G09.  So it should work.
Or do you mean with the same RWF, the output file would be different for the above two versions?

**Comment by abbottjlu** [comment]
Sorry, my mistake. 

The final output file is same.  

It seems I supplied the wrong files for pysoc. 
Sorry for that.
